In [1]:
import numpy as np

In [2]:
a=np.array([3,5,0,9])

In [3]:
a[2]

0

In [5]:
a[1]

5

In [6]:
#Lel's learn about numpy

In [7]:
type(a)

numpy.ndarray

In [10]:
a.ndim

1

In [11]:
a.shape

(4,)

In [12]:
a.size

4

In [13]:
a.dtype

dtype('int64')

In [14]:
#manupulating the arrays

In [15]:
x=np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [17]:
x[0,]

1

In [18]:
x[5,]

6

In [20]:
x[:4]

array([1, 2, 3, 4])

In [21]:
np.save('x',x)

In [22]:
np.load('x.npy')

array([1, 2, 3, 4, 5, 6])